"""Add industries

Revision ID: 07f6ef796d7f
Revises: d7ba96d578f5
Create Date: 2026-04-16 21:07:24.926305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f6ef796d7f'
down_revision: Union[str, Sequence[str], None] = 'd7ba96d578f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries'))
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.add_column('assets', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_assets_industry_id_industries'), 'assets', 'industries', ['industry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_assets_industry_id_industries'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'industry_id')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
