"""Add sector_id to assets

Revision ID: d7ba96d578f5
Revises: 3c85f08c9340
Create Date: 2026-04-16 19:18:03.307081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7ba96d578f5'
down_revision: Union[str, Sequence[str], None] = '3c85f08c9340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('sector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_assets_sector_id_sectors'), 'assets', 'sectors', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_assets_sector_id_sectors'), 'assets', type_='foreignkey')
    op.drop_column('assets', 'sector_id')
    # ### end Alembic commands ###
