"""Add Trading 212 symbol to assets

Revision ID: f50ef0de17c9
Revises: 07f6ef796d7f
Create Date: 2026-04-16 22:11:39.957078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50ef0de17c9'
down_revision: Union[str, Sequence[str], None] = '07f6ef796d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('trading212_symbol', sa.String(), nullable=True))
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('assets', 'trading212_symbol')
    # ### end Alembic commands ###
